### PR TITLE
Beta Release - SM Post Connector

### PR DESCRIPTION
**Pull request by rajanvijayan**
Beta Release - SM Post Connector

### CODE REVIEW

**Review by MohanRaj168 — APPROVED** [review]
LGTM

**Comment by manishsubachchanyadav** [comment]
@rajanvijayan What about the other endpoints ?

image

**Comment by rajanvijayan** [comment]
> @rajanvijayan Need to update the URL structure in the docs.
> 
> image (23)

Static URLs are updated. https://vplugins.github.io/sm-post-connector/create-post.html

**Comment by manishsubachchanyadav** [comment]
LGTM

**Review by manishsubachchanyadav — APPROVED** [review]

**Pull request merged**
