### PR TITLE
Endpoint for Author rendering

### PR DESCRIPTION
**Pull request by manishsubachchanyadav**
- New Endpoint Class: GetAuthors
- Added the get_authors method in the Globals helper class

### CODE REVIEW

**Comment by agopalan87** [comment]
Could you tag the team for any of the plugin changes.

**Comment by manishsubachchanyadav** [comment]
Sure @agopalan87 

@rajanvijayan Can you please review this PR.

**Review by rajanvijayan — APPROVED** [review]

**Comment by rajanvijayan** [comment]
All good for me

**Comment by agopalan87** [comment]
Looks like a new team to be created. Will create one.

**Comment by MohanRaj168** [comment]
It will be good if you share your response for the endpoint that you have created.

**Pull request merged**
